// Urmet cloud HTTP: login (cookie session), fetch+decrypt SIP account, get_my_devices.
import { randomUUID } from "node:crypto";
import { logger } from "./logger.js";
import { decrypt } from "./urmetCrypto.js";

const log = logger("cloud");

const BASE = "https://www.cloud.urmet.com";
const LOGIN = "/tool/index.php";
const SIPDATA = "/tool/multiapi/private/userdata/callme-sdk/sipdata";
const GMD = "/tool/callmeapi/private/get_my_devices";

export interface InstanceAccount {
  username: string;
  password: string;
  realm: string;
}

export interface PlaceData {
  channel_number: string;
  channel_id: string; // INCOMING username
  credentials: string; // INCOMING password (token password)
  out_credentials_username: string; // OUTGOING (gateway-query target)
  out_credentials_password?: string; // OUTGOING password (authenticates the OUTGOING leg)
  uid_type?: string; // raw device MODEL code (e.g. "1060" = IPERCOM, "1760/16" = 2Voice), not a group name
  device_uid?: string;
  Mac_Address?: string;
  device_name?: string; // installation name
  relation_name?: string; // user's own label for the place; preferred for display
}
// A `credentials` / `out_credentials_password` value of "*" is the cloud's placeholder for
// "no such account" - treat it as absent, never as a real password.
export const NO_ACCOUNT = "*";

// Render a get_my_devices entry SAFE to log or share when diagnosing a device. Secrets/identifiers
// are masked to `<str:N>` (a field's presence and length are shown, not its value); only the
// non-sensitive TYPE fields needed for family detection are shown in the clear. Recurses into nested
// objects/arrays so the full structure is visible.
const SHAPE_SAFE_KEYS = new Set([
  "uid_type",
  "call_type",
  "vds_types",
  "device_type",
  "type",
]);
function redactShape(v: unknown, key = ""): unknown {
  if (v === null || v === undefined) return v;
  if (typeof v === "number" || typeof v === "boolean") return v;
  if (typeof v === "string")
    return SHAPE_SAFE_KEYS.has(key) ? v : `<str:${v.length}>`;
  if (Array.isArray(v)) return v.map((x) => redactShape(x, key));
  if (typeof v === "object")
    return Object.fromEntries(
      Object.entries(v as Record<string, unknown>).map(([k, val]) => [
        k,
        redactShape(val, k),
      ]),
    );
  return `<${typeof v}>`;
}

export class Cloud {
  private cookie = "";

  private async req(path: string, init: RequestInit = {}): Promise<Response> {
    const headers = new Headers(init.headers);
    headers.set("User-Agent", "UrmetCallForwarding-Android");
    if (this.cookie) headers.set("Cookie", this.cookie);
    const res = await fetch(BASE + path, {
      ...init,
      headers,
      redirect: "manual",
    });
    log.debug(`${init.method || "GET"} ${path} -> ${res.status}`);
    const setCookie = (res.headers as any).getSetCookie?.() as
      | string[]
      | undefined;
    if (setCookie?.length) {
      const jar = setCookie.map((c) => c.split(";")[0]);
      this.cookie = jar.join("; ");
    }
    return res;
  }

  async login(email: string, password: string): Promise<void> {
    const body = new URLSearchParams({
      httpd_username: email.trim(),
      httpd_password: password.trim(), // both fields are trimmed before submit
    });
    const res = await this.req(LOGIN, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body,
    });
    if (res.status !== 200 && res.status !== 302) {
      throw new Error(`login HTTP ${res.status}`);
    }
    if (!this.cookie) throw new Error("login returned no session cookie");
  }

  async sipAccount(): Promise<InstanceAccount> {
    const res = await this.req(SIPDATA);
    if (res.status !== 200) throw new Error(`sipdata HTTP ${res.status}`);
    const b64 = (await res.text()).replace(/\s+/g, "");
    const plain = decrypt(Buffer.from(b64, "base64")).toString("utf-8");
    const obj = JSON.parse(plain);
    // Credential precedence: use the EXISTING account only when currentSipCredentialsType ==
    // "TYPE_EXISTING" AND it's present; otherwise the autogenerated one. Always preferring
    // autogenerated would register the WRONG SIP identity for an account in existing-credentials mode.
    const order =
      obj.currentSipCredentialsType === "TYPE_EXISTING"
        ? ["existingSipCredentials", "autogeneratedSipCredentials"]
        : ["autogeneratedSipCredentials", "existingSipCredentials"];
    for (const k of order) {
      const acc = obj[k];
      if (acc?.username && acc?.password) {
        return {
          username: acc.username,
          password: acc.password,
          realm: acc.realm,
        };
      }
    }
    throw new Error("no usable SIP credentials in sipdata");
  }

  /** Log in, then fetch the SIP account, retrying a TRANSIENT sipdata redirect. Right after a
   *  (re)install the sipdata GET can 302 to the login page because the freshly-set session cookie
   *  hasn't taken yet; that used to be a fatal `sipdata HTTP 302`. Re-log in (fresh cookie) and retry
   *  a couple of times with a short backoff. A real failure (bad credentials -> login HTTP 4xx, or a
   *  non-redirect sipdata error) is not retried. */
  async loginAndSipAccount(
    email: string,
    password: string,
  ): Promise<InstanceAccount> {
    const attempts = 3;
    for (let attempt = 1; ; attempt++) {
      try {
        await this.login(email, password);
        return await this.sipAccount();
      } catch (e) {
        const msg = (e as Error).message || "";
        const transient = /sipdata HTTP 3\d\d/.test(msg); // a redirect = session not ready yet
        if (!transient || attempt >= attempts) throw e;
        log.warn(
          `${msg}; session not ready, re-logging in and retrying (attempt ${attempt}/${attempts - 1})`,
        );
        await new Promise((r) => setTimeout(r, 1000 * attempt));
      }
    }
  }

  /** Create a DEDICATED per-instance SIP account on the cloud: username
   *  `cfwunique_<email>_<expiry-ts>`, random password. Using a dedicated account (not the shared
   *  autogenerated one, which the phone also registers) gives a clean single registration -
   *  required for the panel to stream video. */
  async createUniqueSipAccount(
    email: string,
    realm: string,
  ): Promise<InstanceAccount> {
    const user = email.trim().replace(/[^a-zA-Z0-9]/g, "_");
    const d = new Date(Date.now() + 180 * 24 * 3600 * 1000); // expiry encoded in the name
    const p = (n: number, l = 2) => String(n).padStart(l, "0");
    const ts =
      p(d.getFullYear() % 100) +
      p(d.getMonth() + 1) +
      p(d.getDate()) +
      p(d.getHours()) +
      p(d.getMinutes()) +
      p(d.getSeconds()) +
      p(d.getMilliseconds(), 3);
    const username = `cfwunique_${user}_${ts}`;
    const password = randomUUID();
    const res = await this.req(
      `/tool/callmeapi/private/create_sip_account_no_mail_confirm/${username}/${realm}/${password}`,
      { method: "POST", body: "" },
    );
    if (res.status !== 200)
      throw new Error(`create_sip_account HTTP ${res.status}`);
    log.info(`created unique SIP account ${username}`);
    return { username, password, realm };
  }

  async getMyDevices(): Promise<PlaceData[]> {
    const res = await this.req(
      `${GMD}?pn-type=android&pn-token=no_android_push_token`,
    );
    if (res.status !== 200)
      throw new Error(`get_my_devices HTTP ${res.status}`);
    const json = (await res.json()) as {
      data?: PlaceData[];
    } & Record<string, unknown>;
    const data = json.data ?? [];
    // At debug level, log each device's REDACTED shape so the get_my_devices field structure for a
    // given device can be inspected safely (secrets masked).
    for (const dev of data) {
      log.debug(`device shape (redacted): ${JSON.stringify(redactShape(dev))}`);
    }
    // Diagnostic for accounts that yield NO places (unsupported model, or devices under a different
    // envelope key): the per-device log above prints nothing when data[] is empty, so dump the whole
    // response shape (redacted) + its top-level keys. This is how we learn where a model like the
    // 1722/58A puts its devices, without exposing any secrets. Ask the user for these two lines.
    if (!data.length) {
      log.debug(
        `get_my_devices returned no data[]; top-level keys: [${Object.keys(json).join(", ")}]`,
      );
      log.debug(
        `get_my_devices response (redacted): ${JSON.stringify(redactShape(json))}`,
      );
    }
    return data;
  }
}
